# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'look_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#
# NOTE: Window-switching and the shared PokemonDatabase *instance* live in
# main.py -- this file never instantiates PokemonDatabase itself and never
# imports top10.py, which is what would reintroduce the circular import.
# Importing TYPE_COLORS (a plain constant, not the class) from
# PokemonDatabase.py below is safe: that module doesn't import top10.py or
# look_up.py, so there's no cycle.


from PyQt5 import QtCore, QtGui, QtWidgets

from PokemonDatabase import TYPE_COLORS, DEFAULT_TYPE_COLOR


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 611)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Search bar box -- filled with the same color as the card border
        # below it (updated together in handle_lookup so they always
        # match the searched Pokemon's type). Created before the label/
        # line edit that sit on top of it so it stacks underneath them.
        self.search_box = QtWidgets.QFrame(self.centralwidget)
        self.search_box.setGeometry(QtCore.QRect(50, 14, 540, 40))
        self.search_box.setObjectName("search_box")
        self.search_box.setStyleSheet(
            "QFrame#search_box {"
            f"background-color: {DEFAULT_TYPE_COLOR};"
            "border-radius: 12px;"
            "}"
        )

        self.lookup_label = QtWidgets.QLabel(self.centralwidget)
        self.lookup_label.setGeometry(QtCore.QRect(70, 22, 150, 24))
        self.lookup_label.setObjectName("lookup_label")
        self.lookup_label.setStyleSheet("color: white; font-weight: bold; font-size: 12pt;")

        self.lookup_line = QtWidgets.QLineEdit(self.centralwidget)
        self.lookup_line.setGeometry(QtCore.QRect(230, 20, 330, 28))
        self.lookup_line.setObjectName("lookup_line")
        self.lookup_line.setStyleSheet(
            "background-color: white;"
            "color: black;"
            "border-radius: 6px;"
            "padding: 2px 8px;"
            "font-size: 11pt;"
        )

        # ------------------------------------------------------------------
        # Result card. Everything below the search bar is styled to look
        # like a Pokemon trading card: a colored frame themed to the
        # Pokemon's type, name + HP at top, a framed sprite, type badges,
        # and a base-stats grid.
        #
        # self.card is created first so every widget added after it draws
        # on top of it (Qt stacks same-parent widgets in creation order).
        # ------------------------------------------------------------------
        # Card was 120,60,400,400 (bottom=460) -- expanded as far as
        # possible while staying clear of the search bar above (bottom
        # ~51) and the buttons below (top=530). Every widget inside is
        # repositioned/resized to fill the extra space, with larger fonts
        # to match.
        self.card = QtWidgets.QFrame(self.centralwidget)
        self.card.setGeometry(QtCore.QRect(50, 55, 540, 465))
        self.card.setObjectName("card")
        self.card.setStyleSheet(
            "QFrame#card {"
            "background-color: rgba(255, 255, 255, 235);"
            "border: 5px solid #777777;"
            "border-radius: 24px;"
            "}"
        )

        # Name (top-left) + HP badge (top-right), like a real card header
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(70, 65, 350, 35))
        self.name.setObjectName("name")
        self.name.setStyleSheet("color: #222222; font-weight: bold; font-size: 22pt;")

        self.hp_badge = QtWidgets.QLabel(self.centralwidget)
        self.hp_badge.setGeometry(QtCore.QRect(430, 68, 150, 30))
        self.hp_badge.setObjectName("hp_badge")
        self.hp_badge.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.hp_badge.setStyleSheet("color: #D0393E; font-weight: bold; font-size: 14pt;")

        # Compact identity row: Pokedex #, height, weight
        self.pokedex_num_label = QtWidgets.QLabel(self.centralwidget)
        self.pokedex_num_label.setGeometry(QtCore.QRect(70, 113, 50, 24))
        self.pokedex_num_label.setObjectName("pokedex_num_label")
        self.pokedex_num = QtWidgets.QLabel(self.centralwidget)
        self.pokedex_num.setGeometry(QtCore.QRect(123, 113, 68, 24))
        self.pokedex_num.setObjectName("pokedex_num")

        self.height_label = QtWidgets.QLabel(self.centralwidget)
        self.height_label.setGeometry(QtCore.QRect(198, 113, 36, 24))
        self.height_label.setObjectName("height_label")
        self.height = QtWidgets.QLabel(self.centralwidget)
        self.height.setGeometry(QtCore.QRect(237, 113, 88, 24))
        self.height.setObjectName("height")

        self.weight_label = QtWidgets.QLabel(self.centralwidget)
        self.weight_label.setGeometry(QtCore.QRect(333, 113, 40, 24))
        self.weight_label.setObjectName("weight_label")
        self.weight = QtWidgets.QLabel(self.centralwidget)
        self.weight.setGeometry(QtCore.QRect(376, 113, 95, 24))
        self.weight.setObjectName("weight")

        for lbl in (self.pokedex_num_label, self.height_label, self.weight_label):
            lbl.setStyleSheet("color: #666666; font-size: 12pt; font-weight: bold;")
        for val in (self.pokedex_num, self.height, self.weight):
            val.setStyleSheet("color: #333333; font-size: 12pt;")

        # Sprite, framed in a small white box for contrast against the card
        self.sprite_frame = QtWidgets.QFrame(self.centralwidget)
        self.sprite_frame.setGeometry(QtCore.QRect(215, 140, 200, 160))
        self.sprite_frame.setObjectName("sprite_frame")
        self.sprite_frame.setStyleSheet(
            "QFrame#sprite_frame {"
            "background-color: white;"
            "border: 2px solid #dddddd;"
            "border-radius: 16px;"
            "}"
        )
        self.sprite = QtWidgets.QPushButton(self.centralwidget)
        self.sprite.setGeometry(QtCore.QRect(235, 140, 160, 160))
        self.sprite.setObjectName("sprite")
        self.sprite.setText("")
        self.sprite.setStyleSheet("QPushButton { border: none; background-color: transparent; } QPushButton:hover { background-color: rgba(200, 200, 200, 50); }")
        self.sprite.setCursor(QtCore.Qt.PointingHandCursor)

        # Left arrow button
        self.sprite_left_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sprite_left_btn.setGeometry(QtCore.QRect(150, 195, 50, 50))
        self.sprite_left_btn.setText("◀")
        self.sprite_left_btn.setObjectName("sprite_left_btn")
        self.sprite_left_btn.setStyleSheet("font-size: 18pt; font-weight: bold; color: black; background-color: transparent; border: none;")

        # Right arrow button
        self.sprite_right_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sprite_right_btn.setGeometry(QtCore.QRect(430, 195, 50, 50))
        self.sprite_right_btn.setText("▶")
        self.sprite_right_btn.setObjectName("sprite_right_btn")
        self.sprite_right_btn.setStyleSheet("font-size: 18pt; font-weight: bold; color: black; background-color: transparent; border: none;")

        # Type badges (pill-shaped, colored per type)
        self.type1 = QtWidgets.QLabel(self.centralwidget)
        self.type1.setGeometry(QtCore.QRect(195, 315, 120, 30))
        self.type1.setObjectName("type1")
        self.type1.setAlignment(QtCore.Qt.AlignCenter)

        self.type2 = QtWidgets.QLabel(self.centralwidget)
        self.type2.setGeometry(QtCore.QRect(325, 315, 120, 30))
        self.type2.setObjectName("type2")
        self.type2.setAlignment(QtCore.Qt.AlignCenter)

        # The old "Type 1:" / "Type 2:" text labels are replaced by the
        # badges above. Kept (hidden, 0-size) so nothing else that might
        # reference these attribute names breaks.
        self.type1_label = QtWidgets.QLabel(self.centralwidget)
        self.type1_label.setGeometry(QtCore.QRect(0, 0, 1, 1))
        self.type1_label.setObjectName("type1_label")
        self.type1_label.setVisible(False)
        self.type2_label = QtWidgets.QLabel(self.centralwidget)
        self.type2_label.setGeometry(QtCore.QRect(0, 0, 1, 1))
        self.type2_label.setObjectName("type2_label")
        self.type2_label.setVisible(False)

        # Add to My Team button
        self.add_to_team_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_to_team_btn.setGeometry(QtCore.QRect(480, 325, 100, 25))
        self.add_to_team_btn.setText("Add to My Team")
        self.add_to_team_btn.setObjectName("add_to_team_btn")
        self.add_to_team_btn.setStyleSheet(
            "QPushButton { color: black; font-size: 10pt; background-color: rgba(255, 255, 255, 220); "
            "border: 1px solid #999999; border-radius: 4px; } "
            "QPushButton:hover { background-color: rgba(255, 255, 255, 240); }"
        )

        # Divider between the badges and the base-stats grid
        self.divider = QtWidgets.QFrame(self.centralwidget)
        self.divider.setGeometry(QtCore.QRect(80, 353, 480, 2))
        self.divider.setObjectName("divider")
        self.divider.setStyleSheet("background-color: #dddddd;")

        # Base stats, laid out as a 2-column grid: (Speed, HP) /
        # (Attack, Defense) / (Sp. Atk, Sp. Def)
        stat_rows = [
            ("speed_label", "speed", "hp_label", "hp", 363),
            ("attack_label", "attack", "defense_label", "defense", 391),
            ("sp_attack_label", "sp_attack", "sp_defense_label", "sp_defense", 419),
        ]
        for a_label_name, a_value_name, b_label_name, b_value_name, y in stat_rows:
            a_label = QtWidgets.QLabel(self.centralwidget)
            a_label.setGeometry(QtCore.QRect(95, y, 115, 30))
            a_label.setObjectName(a_label_name)
            a_value = QtWidgets.QLabel(self.centralwidget)
            a_value.setGeometry(QtCore.QRect(215, y, 65, 30))
            a_value.setObjectName(a_value_name)

            b_label = QtWidgets.QLabel(self.centralwidget)
            b_label.setGeometry(QtCore.QRect(330, y, 115, 30))
            b_label.setObjectName(b_label_name)
            b_value = QtWidgets.QLabel(self.centralwidget)
            b_value.setGeometry(QtCore.QRect(450, y, 65, 30))
            b_value.setObjectName(b_value_name)

            for lbl in (a_label, b_label):
                lbl.setStyleSheet("color: #666666; font-size: 11pt; font-weight: bold;")
            for val in (a_value, b_value):
                val.setStyleSheet("color: #222222; font-size: 11pt; font-weight: bold;")

            setattr(self, a_label_name, a_label)
            setattr(self, a_value_name, a_value)
            setattr(self, b_label_name, b_label)
            setattr(self, b_value_name, b_value)

        # Evolution chain label
        self.evolution_label = QtWidgets.QLabel(self.centralwidget)
        self.evolution_label.setGeometry(QtCore.QRect(70, 495, 510, 20))
        self.evolution_label.setObjectName("evolution_label")
        self.evolution_label.setStyleSheet("color: #666666; font-size: 9pt; font-style: italic;")
        self.evolution_label.setWordWrap(True)
        self.evolution_label.setAlignment(QtCore.Qt.AlignTop)

        # Evolution sprites container
        self.evolution_sprites_frame = QtWidgets.QFrame(self.centralwidget)
        self.evolution_sprites_frame.setGeometry(QtCore.QRect(70, 515, 510, 100))
        self.evolution_sprites_frame.setObjectName("evolution_sprites_frame")

        # Evolution sprite labels (up to 4) - positioned at the bottom of the card, centered
        self.evolution_sprites = []
        sprite_x_positions = [130, 230, 330, 430]
        for i in range(4):
            sprite_btn = QtWidgets.QPushButton(self.centralwidget)
            sprite_btn.setGeometry(QtCore.QRect(sprite_x_positions[i], 450, 60, 60))
            sprite_btn.setObjectName(f"evolution_sprite_{i}")
            sprite_btn.setStyleSheet(
                "QPushButton {"
                "border: 1px solid #ddd; "
                "border-radius: 8px; "
                "background-color: rgba(255,255,255,0.5); "
                "padding: 0px;"
                "}"
                "QPushButton:hover {"
                "border: 2px solid #87CEEB; "
                "background-color: rgba(135,206,235,0.7);"
                "}"
            )
            sprite_btn.setFlat(True)
            self.evolution_sprites.append(sprite_btn)

        # Evolution arrows between sprites
        self.evolution_arrows = []
        arrow_x_positions = [190, 290, 390]
        for i in range(3):
            arrow_label = QtWidgets.QLabel(self.centralwidget)
            arrow_label.setGeometry(QtCore.QRect(arrow_x_positions[i], 465, 40, 30))
            arrow_label.setObjectName(f"evolution_arrow_{i}")
            arrow_label.setText("→")
            arrow_label.setAlignment(QtCore.Qt.AlignCenter)
            arrow_label.setStyleSheet("color: #666666; font-size: 18pt; font-weight: bold; background-color: transparent;")
            self.evolution_arrows.append(arrow_label)

        self.counters_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.counters_b1.setGeometry(QtCore.QRect(20, 530, 140, 30))
        self.counters_b1.setObjectName("counters_b1")
        self.battle_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.battle_b1.setGeometry(QtCore.QRect(170, 530, 140, 30))
        self.battle_b1.setObjectName("battle_b1")

        self.team_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.team_b1.setGeometry(QtCore.QRect(320, 530, 140, 30))
        self.team_b1.setObjectName("team_b1")

        self.top_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.top_b1.setGeometry(QtCore.QRect(470, 530, 140, 30))
        self.top_b1.setObjectName("top_b1")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 651, 581))
        self.background.setText("")
        self.background.setObjectName("background")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 21))
        self.menubar.setObjectName("menubar")
        self.menuLook_Up = QtWidgets.QMenu(self.menubar)
        self.menuLook_Up.setObjectName("menuLook_Up")
        self.menuTop_10 = QtWidgets.QMenu(self.menubar)
        self.menuTop_10.setObjectName("menuTop_10")
        self.menuRaid_Counters = QtWidgets.QMenu(self.menubar)
        self.menuRaid_Counters.setObjectName("menuRaid_Counters")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuLook_Up.menuAction())
        self.menubar.addAction(self.menuTop_10.menuAction())
        self.menubar.addAction(self.menuRaid_Counters.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lookup_label.setText(_translate("MainWindow", "Pokemon Look Up:"))
        self.lookup_line.setPlaceholderText(_translate("MainWindow", "Enter in the Pokemon Name or Number"))

        self.name.setText(_translate("MainWindow", "Search for a Pokémon"))
        self.hp_badge.setText("")

        self.sprite.setText("")

        self.pokedex_num_label.setText(_translate("MainWindow", "No."))
        self.pokedex_num.setText(_translate("MainWindow", "--"))
        self.height_label.setText(_translate("MainWindow", "Ht:"))
        self.height.setText(_translate("MainWindow", "--"))
        self.weight_label.setText(_translate("MainWindow", "Wt:"))
        self.weight.setText(_translate("MainWindow", "--"))

        self.type1.setText("")
        self.type1.setVisible(False)
        self.type2.setText("")
        self.type2.setVisible(False)

        self.hp_label.setText(_translate("MainWindow", "HP:"))
        self.hp.setText(_translate("MainWindow", "--"))
        self.attack_label.setText(_translate("MainWindow", "Attack:"))
        self.attack.setText(_translate("MainWindow", "--"))
        self.defense_label.setText(_translate("MainWindow", "Defense:"))
        self.defense.setText(_translate("MainWindow", "--"))
        self.sp_attack_label.setText(_translate("MainWindow", "Sp. Atk:"))
        self.sp_attack.setText(_translate("MainWindow", "--"))
        self.sp_defense_label.setText(_translate("MainWindow", "Sp. Def:"))
        self.sp_defense.setText(_translate("MainWindow", "--"))
        self.speed_label.setText(_translate("MainWindow", "Speed:"))
        self.speed.setText(_translate("MainWindow", "--"))

        self.counters_b1.setText(_translate("MainWindow", "Raid Counters"))
        self.battle_b1.setText(_translate("MainWindow", "Battle!"))
        self.team_b1.setText(_translate("MainWindow", "My Team"))
        self.top_b1.setText(_translate("MainWindow", "Top 10"))
        self.menuLook_Up.setStatusTip(_translate("MainWindow", "Look up stats for a single Pokemon"))
        self.menuLook_Up.setTitle(_translate("MainWindow", "Look Up"))
        self.menuTop_10.setStatusTip(_translate("MainWindow", "Get the top 10 Pokemon of a specific type"))
        self.menuTop_10.setTitle(_translate("MainWindow", "Top 10"))
        self.menuRaid_Counters.setStatusTip(_translate("MainWindow", "Get raid counters for a specific Pokemon raid boss"))
        self.menuRaid_Counters.setTitle(_translate("MainWindow", "Raid Counters"))


def scale_pixmap_cover(pixmap, target_width, target_height):
    """
    Scale a pixmap to completely fill a target_width x target_height box
    with no distortion (aspect ratio preserved) and no empty space,
    center-cropping whatever overhangs.
    """
    if pixmap.isNull() or target_width <= 0 or target_height <= 0:
        return pixmap

    scaled = pixmap.scaled(
        target_width,
        target_height,
        QtCore.Qt.KeepAspectRatioByExpanding,
        QtCore.Qt.SmoothTransformation
    )

    x = max(0, (scaled.width() - target_width) // 2)
    y = max(0, (scaled.height() - target_height) // 2)

    return scaled.copy(x, y, target_width, target_height)


def set_background(ui):

    # NOTE: called during setupUi(), before the window is shown, so
    # centralwidget.width()/height() isn't reliable yet (see top10.py's
    # set_background for the full explanation). Use the known design size
    # for this fixed-layout window instead.
    widget_width = 651
    widget_height = 581

    pixmap = QtGui.QPixmap("img/poke_background.jpg")
    pixmap = scale_pixmap_cover(pixmap, widget_width, widget_height)

    # Make all labels black by default -- the card's own widgets set
    # their own colors via setStyleSheet, which takes precedence over
    # this cascading default.
    ui.centralwidget.setStyleSheet("""
        QLabel {
            color: black;
            font-weight: bold;

        }
    """)

    # Background
    ui.background.setGeometry(0, 0, widget_width, widget_height)
    ui.background.setPixmap(pixmap)

    # Put background at the very back
    ui.background.lower()

    ui.background_overlay = QtWidgets.QLabel(ui.centralwidget)

    ui.background_overlay.setGeometry(
        0, 0, widget_width, widget_height
    )

    ui.background_overlay.setStyleSheet(
        "background-color: rgba(255, 255, 255, 150);"
    )

    # Don't block buttons
    ui.background_overlay.setAttribute(
        QtCore.Qt.WA_TransparentForMouseEvents
    )

    ui.background_overlay.raise_()

    ui.search_box.raise_()
    ui.lookup_label.raise_()
    ui.lookup_line.raise_()

    ui.card.raise_()
    ui.name.raise_()
    ui.hp_badge.raise_()
    ui.pokedex_num_label.raise_()
    ui.pokedex_num.raise_()
    ui.height_label.raise_()
    ui.height.raise_()
    ui.weight_label.raise_()
    ui.weight.raise_()
    ui.sprite_frame.raise_()
    ui.sprite.raise_()
    ui.sprite_left_btn.raise_()
    ui.sprite_right_btn.raise_()
    ui.type1.raise_()
    ui.type2.raise_()
    ui.add_to_team_btn.raise_()
    ui.divider.raise_()
    ui.hp_label.raise_()
    ui.hp.raise_()
    ui.attack_label.raise_()
    ui.attack.raise_()
    ui.defense_label.raise_()
    ui.defense.raise_()
    ui.sp_attack_label.raise_()
    ui.sp_attack.raise_()
    ui.sp_defense_label.raise_()
    ui.sp_defense.raise_()
    ui.speed_label.raise_()
    ui.speed.raise_()
    ui.evolution_label.raise_()
    for sprite in ui.evolution_sprites:
        sprite.raise_()
    for arrow in ui.evolution_arrows:
        arrow.raise_()
    ui.counters_b1.raise_()
    ui.battle_b1.raise_()
    ui.team_b1.raise_()
    ui.top_b1.raise_()

    ui.counters_b1.setStyleSheet("QPushButton { color: black; font-size: 10pt; background-color: rgba(255, 255, 255, 220); border: 2px solid #333333; border-radius: 6px; box-shadow: 0 12px 24px rgba(0, 0, 0, 0.6); } QPushButton:hover { background-color: rgba(255, 255, 255, 240); box-shadow: 0 16px 32px rgba(0, 0, 0, 0.7); } QPushButton:pressed { background-color: rgba(230, 230, 230, 220); box-shadow: inset 0 4px 8px rgba(0, 0, 0, 0.4), 0 2px 4px rgba(0, 0, 0, 0.3); }")
    ui.battle_b1.setStyleSheet("QPushButton { color: black; font-size: 10pt; background-color: rgba(255, 255, 255, 220); border: 2px solid #333333; border-radius: 6px; box-shadow: 0 12px 24px rgba(0, 0, 0, 0.6); } QPushButton:hover { background-color: rgba(255, 255, 255, 240); box-shadow: 0 16px 32px rgba(0, 0, 0, 0.7); } QPushButton:pressed { background-color: rgba(230, 230, 230, 220); box-shadow: inset 0 4px 8px rgba(0, 0, 0, 0.4), 0 2px 4px rgba(0, 0, 0, 0.3); }")
    ui.team_b1.setStyleSheet("QPushButton { color: black; font-size: 10pt; background-color: rgba(255, 255, 255, 220); border: 2px solid #333333; border-radius: 6px; box-shadow: 0 12px 24px rgba(0, 0, 0, 0.6); } QPushButton:hover { background-color: rgba(255, 255, 255, 240); box-shadow: 0 16px 32px rgba(0, 0, 0, 0.7); } QPushButton:pressed { background-color: rgba(230, 230, 230, 220); box-shadow: inset 0 4px 8px rgba(0, 0, 0, 0.4), 0 2px 4px rgba(0, 0, 0, 0.3); }")
    ui.top_b1.setStyleSheet("QPushButton { color: black; font-size: 10pt; background-color: rgba(255, 255, 255, 220); border: 2px solid #333333; border-radius: 6px; box-shadow: 0 12px 24px rgba(0, 0, 0, 0.6); } QPushButton:hover { background-color: rgba(255, 255, 255, 240); box-shadow: 0 16px 32px rgba(0, 0, 0, 0.7); } QPushButton:pressed { background-color: rgba(230, 230, 230, 220); box-shadow: inset 0 4px 8px rgba(0, 0, 0, 0.4), 0 2px 4px rgba(0, 0, 0, 0.3); }")


def _is_missing(value):
    """True if a stat/type value from the DB is effectively empty (None,
    NaN, or a stringified 'none')."""
    if value is None:
        return True
    if isinstance(value, float) and value != value:  # NaN != NaN
        return True
    if isinstance(value, str) and value.strip().lower() in ("", "none", "nan"):
        return True
    return False


def _style_type_badge(label, type_name):
    color = TYPE_COLORS.get(type_name.lower(), DEFAULT_TYPE_COLOR)
    label.setText(type_name.capitalize())
    label.setStyleSheet(
        f"background-color: {color};"
        "color: white;"
        "font-weight: bold;"
        "font-size: 13pt;"
        "border-radius: 17px;"
        "padding: 2px;"
    )
    label.setVisible(True)


def _navigate_pokemon(ui, pokedex, direction):
    """Navigate to adjacent pokemon by number with wrapping."""
    if not hasattr(ui, 'current_pokemon_no'):
        return

    new_no = ui.current_pokemon_no + direction

    # Wrap around: if new_no > 1025, go to 1; if new_no < 1, go to 1025
    if new_no > 1025:
        new_no = 1
    elif new_no < 1:
        new_no = 1025

    result = pokedex.get_pokemon_by_number(new_no)
    if result is not None and not result.empty:
        poke_data = result.iloc[0].to_dict()
        _display_pokemon_data(ui, pokedex, poke_data)

        # Reconnect sprite click handler when navigating
        try:
            ui.sprite.clicked.disconnect()
        except TypeError:
            pass
        ui.sprite.clicked.connect(lambda: _play_pokemon_cry(ui.current_pokemon_no))


def _display_pokemon_data(ui, pokedex, poke_data):
    """Display pokemon data in the UI."""
    ui.current_pokemon_no = int(poke_data['pokedex_no'])

    # Get sprite
    sprite_data = poke_data.get("sprite")
    if sprite_data:
        pixmap = QtGui.QPixmap()
        pixmap.loadFromData(sprite_data)
        if not pixmap.isNull():
            pixmap = pixmap.scaled(
                165,
                145,
                QtCore.Qt.KeepAspectRatio,
                QtCore.Qt.SmoothTransformation
            )
            icon = QtGui.QIcon(pixmap)
            ui.sprite.setIcon(icon)
            ui.sprite.setIconSize(QtCore.QSize(165, 145))

    # Name + HP
    ui.name.setText(str(poke_data['pokemon']).replace("-", " ").title())
    ui.hp_badge.setText(f"{poke_data['hp']} HP")

    # Identity row
    ui.pokedex_num.setText(f"{int(poke_data['pokedex_no']):03d}")
    ui.height.setText(str(poke_data['height']) + " m")
    ui.weight.setText(str(poke_data['weight']) + " kg")

    # Type badges
    type_1 = poke_data.get('type_1')
    type_2 = poke_data.get('type_2')

    if _is_missing(type_1):
        ui.type1.setVisible(False)
        primary_color = DEFAULT_TYPE_COLOR
    else:
        _style_type_badge(ui.type1, str(type_1))
        primary_color = TYPE_COLORS.get(str(type_1).lower(), DEFAULT_TYPE_COLOR)

    if _is_missing(type_2):
        ui.type2.setVisible(False)
        ui.type1.setGeometry(QtCore.QRect(260, 315, 120, 30))
    else:
        _style_type_badge(ui.type2, str(type_2))
        ui.type1.setGeometry(QtCore.QRect(195, 315, 120, 30))

    ui.card.setStyleSheet(
        "QFrame#card {"
        "background-color: rgba(255, 255, 255, 235);"
        f"border: 5px solid {primary_color};"
        "border-radius: 24px;"
        "}"
    )

    ui.search_box.setStyleSheet(
        "QFrame#search_box {"
        f"background-color: {primary_color};"
        "border-radius: 12px;"
        "}"
    )

    # Base stats
    ui.hp.setText(str(poke_data['hp']))
    ui.attack.setText(str(poke_data['attack']))
    ui.defense.setText(str(poke_data['defense']))
    ui.sp_attack.setText(str(poke_data['special_attack']))
    ui.sp_defense.setText(str(poke_data['special_defense']))
    ui.speed.setText(str(poke_data['speed']))

    # Evolution chain
    evolution_chain = pokedex.get_evolution_chain(str(poke_data['pokemon']))
    if evolution_chain:
        ui.evolution_label.setText("")
        _display_evolution_sprites(ui, pokedex, evolution_chain)
    else:
        ui.evolution_label.setText("")
        for sprite_label in ui.evolution_sprites:
            sprite_label.clear()
            sprite_label.setVisible(False)
        for arrow in ui.evolution_arrows:
            arrow.setVisible(False)


def _display_evolution_sprites(ui, pokedex, evolution_text):
    """Display sprites for each pokemon in the evolution chain."""
    # Parse evolution chain: "Bulbasaur → Ivysaur (Level 16) → Venusaur (Level 32)"
    parts = evolution_text.split(" → ")
    num_pokemon = len(parts[:4])  # Count actual pokemon in chain (max 4)

    # Hide all sprites and arrows first, disconnect click handlers
    for sprite_btn in ui.evolution_sprites:
        sprite_btn.setIcon(QtGui.QIcon())
        sprite_btn.setVisible(False)
        try:
            sprite_btn.clicked.disconnect()
        except TypeError:
            pass
    for arrow in ui.evolution_arrows:
        arrow.setVisible(False)

    if not evolution_text:
        return

    # Show and populate only the needed sprites
    for i, part in enumerate(parts[:4]):
        # Extract pokemon name (before any parentheses)
        pokemon_name = part.split("(")[0].strip()

        # Get sprite from database
        conn = pokedex.get_connection()
        cursor = conn.cursor()
        cursor.execute("SELECT sprite FROM pokedex WHERE LOWER(pokemon) = ?", (pokemon_name.lower(),))
        row = cursor.fetchone()
        conn.close()

        if row and row[0]:
            sprite_data = row[0]
            pixmap = QtGui.QPixmap()
            pixmap.loadFromData(sprite_data)
            if not pixmap.isNull():
                scaled = pixmap.scaled(55, 55, QtCore.Qt.KeepAspectRatio, QtCore.Qt.SmoothTransformation)
                icon = QtGui.QIcon(scaled)
                ui.evolution_sprites[i].setIcon(icon)
                ui.evolution_sprites[i].setIconSize(QtCore.QSize(55, 55))
                ui.evolution_sprites[i].setVisible(True)

                # Connect click handler for this pokemon
                ui.evolution_sprites[i].clicked.connect(
                    lambda checked, pname=pokemon_name, pui=ui, pdb=pokedex: _lookup_pokemon_by_name(pui, pdb, pname)
                )

    # Show arrows between sprites
    for i in range(num_pokemon - 1):
        if i < len(ui.evolution_arrows):
            ui.evolution_arrows[i].setVisible(True)


def _lookup_pokemon_by_name(ui, pokedex, pokemon_name):
    """Look up a pokemon by name and display it."""
    poke_data = pokedex.get_pokemon_by_name(pokemon_name)

    if poke_data is None:
        ui.sprite.setText("Pokemon Not Found")
        ui.name.setText("Not Found")
        ui.hp_badge.setText("")
        ui.type1.setVisible(False)
        ui.type2.setVisible(False)
        ui.evolution_label.setText("")
        return

    # Display pokemon data
    _display_pokemon_data(ui, pokedex, poke_data)

    # Disconnect any previous connections
    try:
        ui.sprite.clicked.disconnect()
        ui.sprite_left_btn.clicked.disconnect()
        ui.sprite_right_btn.clicked.disconnect()
    except TypeError:
        pass

    # Connect sprite click to play cry
    ui.sprite.clicked.connect(lambda: _play_pokemon_cry(ui.current_pokemon_no))

    # Connect carousel buttons
    ui.sprite_left_btn.clicked.connect(lambda: _navigate_pokemon(ui, pokedex, -1))
    ui.sprite_right_btn.clicked.connect(lambda: _navigate_pokemon(ui, pokedex, 1))


def handle_lookup(ui, pokedex):

    # Get the value from the LineEdit and strip Pokedex number if present
    pokemon_input = ui.lookup_line.text().strip()
    # Remove the Pokedex number format " (#480)" if it exists
    if " (#" in pokemon_input:
        pokemon_input = pokemon_input.split(" (#")[0]
    ui.lookup_line.clear()


    # Try to look up by number first if input is numeric
    poke_data = None
    if pokemon_input.isdigit():
        result = pokedex.get_pokemon_by_number(int(pokemon_input))
        if result is not None and not result.empty:
            poke_data = result.iloc[0].to_dict()

    # If not found by number, try by name
    if poke_data is None:
        poke_data = pokedex.get_pokemon_by_name(pokemon_input)

    if poke_data is None:
        ui.sprite.setText("Pokemon Not Found")
        ui.name.setText("Not Found")
        ui.hp_badge.setText("")
        ui.type1.setVisible(False)
        ui.type2.setVisible(False)
        ui.evolution_label.setText("")
        return


    # Display pokemon data and set up carousel
    _display_pokemon_data(ui, pokedex, poke_data)

    # Disconnect any previous connections
    try:
        ui.sprite.clicked.disconnect()
        ui.sprite_left_btn.clicked.disconnect()
        ui.sprite_right_btn.clicked.disconnect()
    except TypeError:
        pass

    # Connect sprite click to play cry
    ui.sprite.clicked.connect(lambda: _play_pokemon_cry(ui.current_pokemon_no))

    # Connect carousel buttons
    ui.sprite_left_btn.clicked.connect(lambda: _navigate_pokemon(ui, pokedex, -1))
    ui.sprite_right_btn.clicked.connect(lambda: _navigate_pokemon(ui, pokedex, 1))


def _play_pokemon_cry(pokemon_id):
    """Play the pokemon cry for the given pokemon ID."""
    try:
        import urllib.request
        import tempfile
        import os
        import pygame
        import threading
        import time
        import json

        # Get pokemon data from PokeAPI to find cry URL
        pokemon_url = f"https://pokeapi.co/api/v2/pokemon/{pokemon_id}/"

        # Create request with User-Agent header
        req = urllib.request.Request(
            pokemon_url,
            headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}
        )
        response = urllib.request.urlopen(req, timeout=5)
        pokemon_data = json.loads(response.read())

        # Try to get cry URL from the pokemon data
        cry_url = pokemon_data.get('cries', {}).get('latest')

        if not cry_url:
            return


        # Download cry to temp file
        try:
            with tempfile.NamedTemporaryFile(delete=False, suffix='.ogg') as tmp:
                temp_path = tmp.name

            # Download using urlopen with timeout
            response = urllib.request.urlopen(cry_url, timeout=5)
            with open(temp_path, 'wb') as f:
                f.write(response.read())

            # Initialize mixer if not already done
            if not pygame.mixer.get_init():
                pygame.mixer.init()

            # Stop any currently playing sound
            pygame.mixer.music.stop()

            # Load and play
            pygame.mixer.music.load(temp_path)
            pygame.mixer.music.play()

            # Clean up temp file after sound finishes
            def cleanup():
                time.sleep(2)
                try:
                    os.unlink(temp_path)
                except Exception as e:
                    pass

            cleanup_thread = threading.Thread(target=cleanup, daemon=True)
            cleanup_thread.start()

        except urllib.error.HTTPError as e:
            pass
        except Exception as e:
            pass

    except Exception as e:
        pass
