# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Background image
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 651, 601))
        self.background.setText("")
        self.background.setObjectName("background")

        # Header
        self.pokedex_header = QtWidgets.QLabel(self.centralwidget)
        self.pokedex_header.setGeometry(QtCore.QRect(250, 10, 150, 30))
        self.pokedex_header.setObjectName("pokedex_header")
        self.pokedex_header.setAlignment(QtCore.Qt.AlignCenter)
        self.pokedex_header.setStyleSheet("color: black; font-weight: bold; font-size: 24pt;")

        # Pokemon image (middle top)
        self.pokemon_pic = QtWidgets.QLabel(self.centralwidget)
        self.pokemon_pic.setGeometry(QtCore.QRect(125, 15, 400, 300))
        self.pokemon_pic.setObjectName("pokemon_pic")
        self.pokemon_pic.setAlignment(QtCore.Qt.AlignCenter)

        # Ash image (between pokemon and buttons)
        self.ash_pic = QtWidgets.QLabel(self.centralwidget)
        self.ash_pic.setGeometry(QtCore.QRect(250, 200, 150, 150))
        self.ash_pic.setObjectName("ash_pic")
        self.ash_pic.setAlignment(QtCore.Qt.AlignCenter)

        # Buttons (two columns, side by side)
        self.lookup_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.lookup_b1.setGeometry(QtCore.QRect(25, 395, 280, 35))
        self.lookup_b1.setObjectName("lookup_b1")

        self.top10_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.top10_b1.setGeometry(QtCore.QRect(335, 395, 280, 35))
        self.top10_b1.setObjectName("top10_b1")

        self.raidcounters_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.raidcounters_b1.setGeometry(QtCore.QRect(25, 445, 280, 35))
        self.raidcounters_b1.setObjectName("raidcounters_b1")

        self.compete_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.compete_b1.setGeometry(QtCore.QRect(335, 445, 280, 35))
        self.compete_b1.setObjectName("compete_b1")

        self.team_builder_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.team_builder_b1.setGeometry(QtCore.QRect(25, 490, 590, 35))
        self.team_builder_b1.setObjectName("team_builder_b1")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 651, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pokédex"))
        self.lookup_b1.setText(_translate("MainWindow", "Look Up Pokémon"))
        self.top10_b1.setText(_translate("MainWindow", "Top 10 by Type"))
        self.raidcounters_b1.setText(_translate("MainWindow", "Raid Counters"))
        self.compete_b1.setText(_translate("MainWindow", "Battle!"))
        self.team_builder_b1.setText(_translate("MainWindow", "Team Builder"))
        self.pokedex_header.setText(_translate("MainWindow", ""))
        self.pokemon_pic.setText("")
        self.ash_pic.setText("")

        set_background(self, "poke_background.jpg")


def scale_pixmap_cover(pixmap, target_width, target_height):
    """
    Scale a pixmap to completely fill a target_width x target_height box
    with no distortion (aspect ratio preserved) and no empty space,
    center-cropping whatever overhangs.
    """
    if pixmap.isNull() or target_width <= 0 or target_height <= 0:
        return pixmap

    scaled = pixmap.scaled(
        target_width,
        target_height,
        QtCore.Qt.KeepAspectRatioByExpanding,
        QtCore.Qt.SmoothTransformation
    )

    x = max(0, (scaled.width() - target_width) // 2)
    y = max(0, (scaled.height() - target_height) // 2)

    return scaled.copy(x, y, target_width, target_height)


def set_background(ui, name_of_background):

    widget_width = 651
    widget_height = 601

    pixmap = QtGui.QPixmap("img/" + name_of_background)
    pixmap = scale_pixmap_cover(pixmap, widget_width, widget_height)

    ui.centralwidget.setStyleSheet("""
        QLabel {
            color: black;
            font-weight: bold;
        }
    """)

    ui.background.setGeometry(0, 0, widget_width, widget_height)
    ui.background.setPixmap(pixmap)

    ui.background.lower()

    ui.background_overlay = QtWidgets.QLabel(ui.centralwidget)
    ui.background_overlay.setGeometry(0, 0, widget_width, widget_height)
    ui.background_overlay.setStyleSheet(
        "background-color: rgba(255, 255, 255, 150);"
    )
    ui.background_overlay.setAttribute(
        QtCore.Qt.WA_TransparentForMouseEvents
    )

    ui.background_overlay.raise_()
    ui.pokedex_header.raise_()
    ui.pokemon_pic.raise_()
    ui.ash_pic.raise_()
    ui.lookup_b1.raise_()
    ui.top10_b1.raise_()
    ui.raidcounters_b1.raise_()
    ui.compete_b1.raise_()
    ui.team_builder_b1.raise_()

    button_style = "QPushButton { color: black; font-size: 12pt; font-weight: bold; border: 2px solid #333333; border-radius: 6px; background-color: rgba(255, 255, 255, 220); box-shadow: 0 12px 24px rgba(0, 0, 0, 0.6); } QPushButton:hover { background-color: rgba(255, 255, 255, 240); box-shadow: 0 16px 32px rgba(0, 0, 0, 0.7); } QPushButton:pressed { background-color: rgba(230, 230, 230, 220); box-shadow: inset 0 4px 8px rgba(0, 0, 0, 0.4), 0 2px 4px rgba(0, 0, 0, 0.3); }"
    ui.lookup_b1.setStyleSheet(button_style)
    ui.top10_b1.setStyleSheet(button_style)
    ui.raidcounters_b1.setStyleSheet(button_style)
    ui.compete_b1.setStyleSheet(button_style)
    ui.team_builder_b1.setStyleSheet(button_style)


def load_image(label, image_path, max_width=150, max_height=250):
    """Load an image from file into a label, scaled to fit."""
    pixmap = QtGui.QPixmap(image_path)
    if not pixmap.isNull():
        scaled = pixmap.scaled(
            max_width,
            max_height,
            QtCore.Qt.KeepAspectRatio,
            QtCore.Qt.SmoothTransformation
        )
        label.setPixmap(scaled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    # Load the images
    load_image(ui.pokemon_pic, "img/pokemon.png")
    # load_image(ui.ash_pic, "img/ash.jpg")  # Commented out until ash.jpg is added

    MainWindow.show()
    sys.exit(app.exec_())
