# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raidcounters.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#
# NOTE: Window-switching and the shared PokemonDatabase *instance* live in
# main.py -- this file never imports top10.py or look_up.py, which is what
# would reintroduce the circular import. Importing TYPE_COLORS (a plain
# constant, not the class) from PokemonDatabase.py below is safe: that
# module doesn't import top10.py or look_up.py, so there's no cycle.
#
# Styled to match top10.py / look_up.py: a colored search box, a rounded
# card themed to the raid boss's type, and a numbered 1-5 list of the
# best counters (each with a sprite), the same visual language as the
# rest of the app.


from PyQt5 import QtCore, QtGui, QtWidgets

from PokemonDatabase import TYPE_COLORS, DEFAULT_TYPE_COLOR


class Ui_RaidCounters(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 611)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 651, 581))
        self.background.setText("")
        self.background.setObjectName("background")

        # Search bar box -- filled with the same color as the card border
        # below it (updated together in handle_raid_counters so they
        # always match the raid boss's type). Created before the label/
        # line edit that sit on top of it so it stacks underneath them.
        self.search_box = QtWidgets.QFrame(self.centralwidget)
        self.search_box.setGeometry(QtCore.QRect(140, 58, 370, 40))
        self.search_box.setObjectName("search_box")
        self.search_box.setStyleSheet(
            "QFrame#search_box {"
            f"background-color: {DEFAULT_TYPE_COLOR};"
            "border-radius: 12px;"
            "}"
        )

        self.raid_pokemon_label = QtWidgets.QLabel(self.centralwidget)
        self.raid_pokemon_label.setGeometry(QtCore.QRect(160, 66, 130, 24))
        self.raid_pokemon_label.setObjectName("raid_pokemon_label")
        self.raid_pokemon_label.setStyleSheet("color: white; font-weight: bold; font-size: 12pt;")

        self.raid_pokemon = QtWidgets.QLineEdit(self.centralwidget)
        self.raid_pokemon.setGeometry(QtCore.QRect(300, 64, 180, 28))
        self.raid_pokemon.setObjectName("raid_pokemon")
        self.raid_pokemon.setStyleSheet(
            "background-color: white;"
            "color: black;"
            "border-radius: 6px;"
            "padding: 2px 8px;"
            "font-size: 11pt;"
        )

        # ------------------------------------------------------------------
        # Result card -- rounded frame themed to the raid boss's type, a
        # colored badge title, and the top-5 counters as a numbered list,
        # each with its sprite.
        #
        # self.card is created first so every widget added after it draws
        # on top of it (Qt stacks same-parent widgets in creation order).
        # ------------------------------------------------------------------
        self.card = QtWidgets.QFrame(self.centralwidget)
        self.card.setGeometry(QtCore.QRect(140, 108, 370, 372))
        self.card.setObjectName("card")
        self.card.setStyleSheet(
            "QFrame#card {"
            "background-color: rgba(255, 255, 255, 235);"
            "border: 5px solid #777777;"
            "border-radius: 22px;"
            "}"
        )

        # Badge / title, centered at the top of the card
        self.raid_pokemon_header = QtWidgets.QLabel(self.centralwidget)
        self.raid_pokemon_header.setGeometry(QtCore.QRect(190, 122, 260, 28))
        self.raid_pokemon_header.setObjectName("raid_pokemon_header")
        self.raid_pokemon_header.setAlignment(QtCore.Qt.AlignCenter)

        # Divider between the badge and the counters list
        self.divider = QtWidgets.QFrame(self.centralwidget)
        self.divider.setGeometry(QtCore.QRect(170, 158, 310, 2))
        self.divider.setObjectName("divider")
        self.divider.setStyleSheet("background-color: #dddddd;")

        # Counters list, ranked 1-5, each with a sprite thumbnail
        counter_rows = [168, 230, 292, 354, 416]
        for i, y in enumerate(counter_rows, start=1):
            # Sprite button (clickable)
            sprite_btn = QtWidgets.QPushButton(self.centralwidget)
            sprite_btn.setGeometry(QtCore.QRect(170, y, 56, 56))
            sprite_name = f"sprite{i}"
            sprite_btn.setObjectName(sprite_name)
            sprite_btn.setStyleSheet("border: none; padding: 0px; background-color: transparent;")
            sprite_btn.setFlat(True)
            setattr(self, sprite_name, sprite_btn)

            # Pokemon name button (clickable)
            name_btn = QtWidgets.QPushButton(self.centralwidget)
            name_btn.setGeometry(QtCore.QRect(240, y + 16, 190, 24))
            name = f"pokemon{i}"
            name_btn.setObjectName(name)
            name_btn.setStyleSheet(
                "QPushButton {"
                "font-size: 12pt; font-weight: bold; color: black; "
                "text-align: left; padding-left: 4px; "
                "border: none; background-color: transparent;"
                "}"
                "QPushButton:hover {"
                "background-color: rgba(173,216,230,0.3);"
                "}"
            )
            name_btn.setFlat(True)
            setattr(self, name, name_btn)

            # Type badge label 1
            type_badge = QtWidgets.QLabel(self.centralwidget)
            type_badge.setGeometry(QtCore.QRect(360, y + 16, 50, 24))
            type_name = f"type{i}"
            type_badge.setObjectName(type_name)
            type_badge.setAlignment(QtCore.Qt.AlignCenter)
            type_badge.setStyleSheet("font-size: 8pt; font-weight: bold; border-radius: 4px; padding: 2px;")
            setattr(self, type_name, type_badge)

            # Type badge label 2
            type_badge2 = QtWidgets.QLabel(self.centralwidget)
            type_badge2.setGeometry(QtCore.QRect(415, y + 16, 50, 24))
            type_name2 = f"type{i}_2"
            type_badge2.setObjectName(type_name2)
            type_badge2.setAlignment(QtCore.Qt.AlignCenter)
            type_badge2.setStyleSheet("font-size: 8pt; font-weight: bold; border-radius: 4px; padding: 2px;")
            setattr(self, type_name2, type_badge2)

        self.lookup_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.lookup_b1.setGeometry(QtCore.QRect(20, 530, 140, 30))
        self.lookup_b1.setObjectName("lookup_b1")
        self.battle_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.battle_b1.setGeometry(QtCore.QRect(172, 530, 140, 30))
        self.battle_b1.setObjectName("battle_b1")

        self.team_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.team_b1.setGeometry(QtCore.QRect(324, 530, 140, 30))
        self.team_b1.setObjectName("team_b1")

        self.top_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.top_b1.setGeometry(QtCore.QRect(476, 530, 140, 30))
        self.top_b1.setObjectName("top_b1")

        self.type_chart_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.type_chart_b1.setGeometry(QtCore.QRect(610, 10, 30, 30))
        self.type_chart_b1.setObjectName("type_chart_b1")
        self.type_chart_b1.setText("📊")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.raid_pokemon_label.setText(_translate("MainWindow", "Raid Pokemon:"))
        self.raid_pokemon.setPlaceholderText(_translate("MainWindow", "Raid Boss Name or Number"))

        self.raid_pokemon_header.setText(_translate("MainWindow", "RAID COUNTERS"))
        self.raid_pokemon_header.setStyleSheet(
            f"background-color: {DEFAULT_TYPE_COLOR};"
            "color: white;"
            "font-weight: bold;"
            "font-size: 11pt;"
            "border-radius: 14px;"
            "padding: 2px;"
        )

        for i in range(1, 6):
            getattr(self, f"pokemon{i}").setText(_translate("MainWindow", f"{i}. --"))

        self.lookup_b1.setText(_translate("MainWindow", "Look Up"))
        self.battle_b1.setText(_translate("MainWindow", "Battle!"))
        self.team_b1.setText(_translate("MainWindow", "My Team"))
        self.top_b1.setText(_translate("MainWindow", "Top 10"))

        set_background(self, "poke_background.jpg")

        # Signal wiring (raid_pokemon.returnPressed, lookup_b1.clicked,
        # top_b1.clicked) is done in main.py, since it needs the shared
        # pokedex and window-switching logic that this file no longer has
        # access to.


def scale_pixmap_cover(pixmap, target_width, target_height):
    """
    Scale a pixmap to completely fill a target_width x target_height box
    with no distortion (aspect ratio preserved) and no empty space,
    center-cropping whatever overhangs.
    """
    if pixmap.isNull() or target_width <= 0 or target_height <= 0:
        return pixmap

    scaled = pixmap.scaled(
        target_width,
        target_height,
        QtCore.Qt.KeepAspectRatioByExpanding,
        QtCore.Qt.SmoothTransformation
    )

    x = max(0, (scaled.width() - target_width) // 2)
    y = max(0, (scaled.height() - target_height) // 2)

    return scaled.copy(x, y, target_width, target_height)


def darken_color(hex_color, factor=0.6):
    """Darken a hex color by multiplying RGB values by factor (0-1)."""
    hex_color = hex_color.lstrip('#')
    r = int(hex_color[0:2], 16)
    g = int(hex_color[2:4], 16)
    b = int(hex_color[4:6], 16)

    r = max(0, int(r * factor))
    g = max(0, int(g * factor))
    b = max(0, int(b * factor))

    return f"#{r:02x}{g:02x}{b:02x}"


def set_background(ui, name_of_background, pokemon_type=None):

    # NOTE: called during setupUi(), before the window is shown, so
    # centralwidget.width()/height() isn't reliable yet (see top10.py's
    # set_background for the full explanation). Use the known design size
    # for this fixed-layout window instead.
    widget_width = 651
    widget_height = 581

    # Make all labels black by default -- the card's own widgets set
    # their own colors via setStyleSheet, which takes precedence over
    # this cascading default.
    ui.centralwidget.setStyleSheet("""
        QLabel {
            color: black;
            font-weight: bold;

        }
    """)

    ui.background.setGeometry(0, 0, widget_width, widget_height)

    # If type provided, use darkened type color; otherwise use background image
    if pokemon_type and pokemon_type in TYPE_COLORS:
        background_color = darken_color(TYPE_COLORS[pokemon_type], factor=0.6)
        # Clear any existing pixmap first
        ui.background.setPixmap(QtGui.QPixmap())
        ui.background.setStyleSheet(f"background-color: {background_color};")
        # Delete overlay if it exists
        if hasattr(ui, 'background_overlay') and ui.background_overlay is not None:
            try:
                ui.background_overlay.deleteLater()
            except RuntimeError:
                pass
            ui.background_overlay = None
    else:
        # Load default background image with overlay baked in
        ui.background.setStyleSheet("")  # Clear stylesheet
        pixmap = QtGui.QPixmap("img/poke_background.jpg")
        pixmap = scale_pixmap_cover(pixmap, widget_width, widget_height)

        # Create overlay painter on the pixmap
        painter = QtGui.QPainter(pixmap)
        painter.fillRect(pixmap.rect(), QtGui.QColor(255, 255, 255, 150))
        painter.end()

        ui.background.setPixmap(pixmap)

        # Delete old overlay if it exists
        if hasattr(ui, 'background_overlay') and ui.background_overlay is not None:
            try:
                ui.background_overlay.deleteLater()
            except RuntimeError:
                pass
            ui.background_overlay = None

    # Put background at the very back
    ui.background.lower()

    # Delete old overlay if it exists
    if hasattr(ui, 'background_overlay') and ui.background_overlay is not None:
        ui.background_overlay.deleteLater()

    ui.search_box.raise_()
    ui.raid_pokemon_label.raise_()
    ui.raid_pokemon.raise_()

    ui.card.raise_()
    ui.raid_pokemon_header.raise_()
    ui.divider.raise_()
    for i in range(1, 6):
        getattr(ui, f"sprite{i}").raise_()
        getattr(ui, f"pokemon{i}").raise_()
        getattr(ui, f"type{i}").raise_()
        getattr(ui, f"type{i}_2").raise_()

    ui.lookup_b1.raise_()
    ui.battle_b1.raise_()
    ui.team_b1.raise_()
    ui.top_b1.raise_()
    ui.type_chart_b1.raise_()

    button_style = "QPushButton { color: black; font-size: 10pt; background-color: rgba(255, 255, 255, 220); border: 2px solid #333333; border-radius: 6px; box-shadow: 0 12px 24px rgba(0, 0, 0, 0.6); } QPushButton:hover { background-color: rgba(255, 255, 255, 240); box-shadow: 0 16px 32px rgba(0, 0, 0, 0.7); } QPushButton:pressed { background-color: rgba(230, 230, 230, 220); box-shadow: inset 0 4px 8px rgba(0, 0, 0, 0.4), 0 2px 4px rgba(0, 0, 0, 0.3); }"
    ui.lookup_b1.setStyleSheet(button_style)
    ui.battle_b1.setStyleSheet(button_style)
    ui.team_b1.setStyleSheet(button_style)
    ui.top_b1.setStyleSheet(button_style)
    ui.type_chart_b1.setStyleSheet("QPushButton { color: black; font-size: 14pt; background-color: rgba(255, 255, 255, 220); border: 2px solid #333333; border-radius: 6px; box-shadow: 0 12px 24px rgba(0, 0, 0, 0.6); } QPushButton:hover { background-color: rgba(255, 255, 255, 240); box-shadow: 0 16px 32px rgba(0, 0, 0, 0.7); } QPushButton:pressed { background-color: rgba(230, 230, 230, 220); box-shadow: inset 0 4px 8px rgba(0, 0, 0, 0.4), 0 2px 4px rgba(0, 0, 0, 0.3); }")


def _is_missing(value):
    """True if a stat/type value from the DB is effectively empty (None,
    NaN, or a stringified 'none')."""
    if value is None:
        return True
    if isinstance(value, float) and value != value:  # NaN != NaN
        return True
    if isinstance(value, str) and value.strip().lower() in ("", "none", "nan"):
        return True
    return False


def handle_raid_counters(ui, pokedex, on_pokemon_click=None):

    # Get the value from the LineEdit and strip Pokedex number if present
    raid_boss = ui.raid_pokemon.text().strip()
    # Remove the Pokedex number format " (#480)" if it exists
    if " (#" in raid_boss:
        raid_boss = raid_boss.split(" (#")[0]
    ui.raid_pokemon.clear()

    print("User entered: ", raid_boss)

    counters = pokedex.get_raid_counters(raid_boss)

    if counters is None:
        set_background(ui, "poke_background.jpg", pokemon_type=None)
        ui.raid_pokemon_header.setText("Raid Boss Not Found")
        ui.raid_pokemon_header.setStyleSheet(
            f"background-color: {DEFAULT_TYPE_COLOR};"
            "color: white;"
            "font-weight: bold;"
            "font-size: 11pt;"
            "border-radius: 14px;"
            "padding: 2px;"
        )
        ui.card.setStyleSheet(
            "QFrame#card {"
            "background-color: rgba(255, 255, 255, 235);"
            f"border: 5px solid {DEFAULT_TYPE_COLOR};"
            "border-radius: 22px;"
            "}"
        )
        ui.search_box.setStyleSheet(
            "QFrame#search_box {"
            f"background-color: {DEFAULT_TYPE_COLOR};"
            "border-radius: 12px;"
            "}"
        )
        for i in range(1, 6):
            getattr(ui, f"pokemon{i}").setText(f"{i}. --")
            getattr(ui, f"sprite{i}").setIcon(QtGui.QIcon())
        return

    print(counters)

    # Get the actual Pokemon name (in case user entered a number)
    boss_data = None
    boss_display_name = raid_boss.title()

    # Try to parse as a number first
    try:
        boss_num = int(raid_boss)
        result = pokedex.get_pokemon_by_number(boss_num)
        if result is not None and not result.empty:
            boss_data = result.iloc[0].to_dict()
            boss_display_name = str(boss_data['pokemon']).title()
    except (ValueError, TypeError):
        # If not a number, try by name
        boss_data = pokedex.get_pokemon_by_name(raid_boss)
        if boss_data is not None:
            boss_display_name = str(boss_data.get('pokemon', raid_boss)).title()

    # Theme the card/background off the raid boss's own type (the
    # counters themselves are Pokemon strong *against* that type)
    boss_type = None
    if boss_data is not None and not _is_missing(boss_data.get('type_1')):
        boss_type = str(boss_data['type_1']).lower()

    color = TYPE_COLORS.get(boss_type, DEFAULT_TYPE_COLOR)
    name_of_background = f"{boss_type}.jpg" if boss_type else "poke_background.jpg"
    set_background(ui, name_of_background, pokemon_type=boss_type)

    # Include Pokedex number if available
    header_text = f"Counters for {boss_display_name}"
    if boss_data is not None and 'pokedex_no' in boss_data:
        pokedex_no = boss_data['pokedex_no']
        header_text = f"Counters for {boss_display_name} (#{pokedex_no})"
    ui.raid_pokemon_header.setText(header_text)
    ui.raid_pokemon_header.setStyleSheet(
        f"background-color: {color};"
        "color: white;"
        "font-weight: bold;"
        "font-size: 11pt;"
        "border-radius: 14px;"
        "padding: 2px;"
    )
    ui.card.setStyleSheet(
        "QFrame#card {"
        "background-color: rgba(255, 255, 255, 235);"
        f"border: 5px solid {color};"
        "border-radius: 22px;"
        "}"
    )
    ui.search_box.setStyleSheet(
        "QFrame#search_box {"
        f"background-color: {color};"
        "border-radius: 12px;"
        "}"
    )

    # Results, ranked 1-5, each with its sprite. get_raid_counters() can
    # return fewer than 5 rows (if fewer than 5 Pokemon match the
    # weakness criteria), so only fill in what we actually got and clear
    # out any remaining rows from a previous search.
    names = counters["pokemon"].tolist()
    for i in range(5):
        rank = i + 1
        pokemon_btn = getattr(ui, f"pokemon{rank}")
        sprite_btn = getattr(ui, f"sprite{rank}")
        type_badge = getattr(ui, f"type{rank}")

        if i >= len(names):
            pokemon_btn.setText(f"{rank}. --")
            sprite_btn.setIcon(QtGui.QIcon())
            type_badge.clear()
            continue

        name = str(names[i])
        pokemon_btn.setText(f"{rank}. {name.title()}")

        detail = pokedex.get_pokemon_by_name(name)
        sprite_data = detail.get("sprite") if detail is not None else None

        if sprite_data:
            pixmap = QtGui.QPixmap()
            pixmap.loadFromData(sprite_data)
            pixmap = pixmap.scaled(
                56,
                56,
                QtCore.Qt.KeepAspectRatio,
                QtCore.Qt.SmoothTransformation
            )
            icon = QtGui.QIcon(pixmap)
            sprite_btn.setIcon(icon)
            sprite_btn.setIconSize(QtCore.QSize(56, 56))
        else:
            sprite_btn.setIcon(QtGui.QIcon())

        # Set up click handlers
        try:
            pokemon_btn.clicked.disconnect()
            sprite_btn.clicked.disconnect()
        except TypeError:
            pass

        if on_pokemon_click:
            pokemon_btn.clicked.connect(lambda checked, pname=name: on_pokemon_click(pname))
            sprite_btn.clicked.connect(lambda checked, pname=name: on_pokemon_click(pname))
        else:
            pokemon_btn.clicked.connect(lambda checked, pname=name, pui=ui, pdb=pokedex: _lookup_pokemon_raid(pui, pdb, pname))
            sprite_btn.clicked.connect(lambda checked, pname=name, pui=ui, pdb=pokedex: _lookup_pokemon_raid(pui, pdb, pname))

        # Display type badges
        if detail is not None:
            type_1 = detail.get('type_1')
            type_2 = detail.get('type_2')
            type_badge = getattr(ui, f"type{rank}")
            type_badge2 = getattr(ui, f"type{rank}_2")

            if type_1 and not _is_missing(type_1):
                type_color = TYPE_COLORS.get(str(type_1).lower(), DEFAULT_TYPE_COLOR)
                type_badge.setText(str(type_1).capitalize())
                type_badge.setStyleSheet(
                    f"font-size: 8pt; font-weight: bold; border-radius: 4px; padding: 2px; "
                    f"background-color: {type_color}; color: white;"
                )

            if type_2 and not _is_missing(type_2):
                import pandas as pd
                if pd.notna(type_2):
                    type_color2 = TYPE_COLORS.get(str(type_2).lower(), DEFAULT_TYPE_COLOR)
                    type_badge2.setText(str(type_2).capitalize())
                    type_badge2.setStyleSheet(
                        f"font-size: 8pt; font-weight: bold; border-radius: 4px; padding: 2px; "
                        f"background-color: {type_color2}; color: white;"
                    )
                    type_badge2.show()
                else:
                    type_badge2.hide()
            else:
                type_badge2.hide()


def _lookup_pokemon_raid(ui, pokedex, pokemon_name):
    """Look up a pokemon from raid counters click and display it in lookup window."""
    import look_up

    poke_data = pokedex.get_pokemon_by_name(pokemon_name)
    if poke_data is None:
        return

    # Use the lookup function to display the pokemon
    look_up._lookup_pokemon_by_name(ui, pokedex, pokemon_name)


if __name__ == "__main__":
    import sys

    from PokemonDatabase import PokemonDatabase

    app = QtWidgets.QApplication(sys.argv)

    pokedex = PokemonDatabase()

    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_RaidCounters()
    ui.setupUi(MainWindow)

    ui.raid_pokemon.returnPressed.connect(
        lambda: handle_raid_counters(ui, pokedex)
    )

    MainWindow.show()

    sys.exit(app.exec_())
