# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Top10.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#
# NOTE: Window-switching and the PokemonDatabase *instance* now live in
# main.py -- this file never imports look_up.py, which is what would
# reintroduce the circular import. Importing TYPE_COLORS (a plain
# constant, not the class) from PokemonDatabase.py below is safe: that
# module doesn't import top10.py or look_up.py, so there's no cycle.


import pandas as pd
from PyQt5 import QtCore, QtGui, QtWidgets

from PokemonDatabase import TYPE_COLORS, DEFAULT_TYPE_COLOR


class Ui_Top10(object):
    def setupUi(self, Top10):
        Top10.setObjectName("Top10")
        Top10.resize(645, 595)
        self.centralwidget = QtWidgets.QWidget(Top10)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 651, 561))
        self.background.setText("")
        self.background.setObjectName("background")
        # Search bar box -- filled with the same color as the card border
        # below it (updated together in handle_top so they always match
        # the searched type). Created before the label/line edit that sit
        # on top of it so it stacks underneath them.
        self.search_box = QtWidgets.QFrame(self.centralwidget)
        self.search_box.setGeometry(QtCore.QRect(140, 58, 370, 40))
        self.search_box.setObjectName("search_box")
        self.search_box.setStyleSheet(
            "QFrame#search_box {"
            f"background-color: {DEFAULT_TYPE_COLOR};"
            "border-radius: 12px;"
            "}"
        )

        self.type_label = QtWidgets.QLabel(self.centralwidget)
        self.type_label.setGeometry(QtCore.QRect(160, 66, 130, 24))
        self.type_label.setObjectName("type_label")
        self.type_label.setStyleSheet("color: white; font-weight: bold; font-size: 12pt;")

        self.type = QtWidgets.QLineEdit(self.centralwidget)
        self.type.setGeometry(QtCore.QRect(300, 64, 180, 28))
        self.type.setWhatsThis("")
        self.type.setAccessibleDescription("")
        self.type.setObjectName("type")
        self.type.setStyleSheet(
            "background-color: white;"
            "color: black;"
            "border-radius: 6px;"
            "padding: 2px 8px;"
            "font-size: 11pt;"
        )

        # ------------------------------------------------------------------
        # Result card -- styled to match look_up.py's Pokemon-card look: a
        # rounded frame themed to the searched type's color, a colored
        # type-badge title, and the top-10 results as a numbered 1-10 list.
        #
        # self.card is created first so every widget added after it draws
        # on top of it (Qt stacks same-parent widgets in creation order).
        # ------------------------------------------------------------------
        self.card = QtWidgets.QFrame(self.centralwidget)
        self.card.setGeometry(QtCore.QRect(140, 108, 370, 372))
        self.card.setObjectName("card")
        self.card.setStyleSheet(
            "QFrame#card {"
            "background-color: rgba(255, 255, 255, 235);"
            "border: 5px solid #777777;"
            "border-radius: 22px;"
            "}"
        )

        # Type badge / title, centered at the top of the card
        self.type_header = QtWidgets.QLabel(self.centralwidget)
        self.type_header.setGeometry(QtCore.QRect(245, 122, 160, 28))
        self.type_header.setFrameShadow(QtWidgets.QFrame.Plain)
        self.type_header.setObjectName("type_header")
        self.type_header.setAlignment(QtCore.Qt.AlignCenter)

        # Divider between the badge and the results list
        self.divider = QtWidgets.QFrame(self.centralwidget)
        self.divider.setGeometry(QtCore.QRect(170, 158, 310, 2))
        self.divider.setObjectName("divider")
        self.divider.setStyleSheet("background-color: #dddddd;")

        # Results list, ranked 1-10 (31px spacing to fit all rows in card without sprite overlap)
        pokemon_rows = [168, 199, 230, 261, 292, 323, 354, 385, 416, 447]
        self.pokemon_buttons = []  # Store buttons for click handling
        for i, y in enumerate(pokemon_rows, start=1):
            # Pokemon sprite button (clickable)
            sprite_btn = QtWidgets.QPushButton(self.centralwidget)
            sprite_btn.setGeometry(QtCore.QRect(180, y-4, 32, 32))
            sprite_name = f"sprite{i}"
            sprite_btn.setObjectName(sprite_name)
            sprite_btn.setStyleSheet("border: none; padding: 0px; background-color: transparent;")
            sprite_btn.setFlat(True)
            setattr(self, sprite_name, sprite_btn)
            self.pokemon_buttons.append((sprite_btn, i))

            # Pokemon name button (clickable)
            name_btn = QtWidgets.QPushButton(self.centralwidget)
            name_btn.setGeometry(QtCore.QRect(220, y, 160, 24))
            name = f"pokemon{i}"
            name_btn.setObjectName(name)
            name_btn.setStyleSheet(
                "QPushButton {"
                "font-size: 11pt; "
                "color: black; "
                "text-align: left; "
                "padding-left: 4px; "
                "border: none; "
                "background-color: transparent;"
                "}"
                "QPushButton:hover {"
                "background-color: rgba(173,216,230,0.3);"
                "}"
            )
            name_btn.setFlat(True)
            setattr(self, name, name_btn)
            self.pokemon_buttons.append((name_btn, i))

            # Type badge label 1
            type_badge = QtWidgets.QLabel(self.centralwidget)
            type_badge.setGeometry(QtCore.QRect(340, y, 50, 24))
            type_name = f"type{i}"
            type_badge.setObjectName(type_name)
            type_badge.setAlignment(QtCore.Qt.AlignCenter)
            type_badge.setStyleSheet("font-size: 8pt; font-weight: bold; border-radius: 4px; padding: 2px;")
            setattr(self, type_name, type_badge)

            # Type badge label 2
            type_badge2 = QtWidgets.QLabel(self.centralwidget)
            type_badge2.setGeometry(QtCore.QRect(395, y, 50, 24))
            type_name2 = f"type{i}_2"
            type_badge2.setObjectName(type_name2)
            type_badge2.setAlignment(QtCore.Qt.AlignCenter)
            type_badge2.setStyleSheet("font-size: 8pt; font-weight: bold; border-radius: 4px; padding: 2px;")
            setattr(self, type_name2, type_badge2)

            # Total stats label
            stats_label = QtWidgets.QLabel(self.centralwidget)
            stats_label.setGeometry(QtCore.QRect(435, y, 70, 24))
            stats_name = f"stats{i}"
            stats_label.setObjectName(stats_name)
            stats_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
            stats_label.setStyleSheet("font-size: 9pt; font-weight: bold; color: #222222; padding-right: 4px;")
            setattr(self, stats_name, stats_label)

        self.raidCounters_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.raidCounters_b1.setGeometry(QtCore.QRect(20, 510, 140, 30))
        self.raidCounters_b1.setObjectName("raidCounters_b1")
        self.battle_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.battle_b1.setGeometry(QtCore.QRect(177, 510, 140, 30))
        self.battle_b1.setObjectName("battle_b1")

        self.team_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.team_b1.setGeometry(QtCore.QRect(334, 510, 140, 30))
        self.team_b1.setObjectName("team_b1")

        self.lookup_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.lookup_b1.setGeometry(QtCore.QRect(491, 510, 140, 30))
        self.lookup_b1.setObjectName("lookup_b1")

        self.type_chart_b1 = QtWidgets.QPushButton(self.centralwidget)
        self.type_chart_b1.setGeometry(QtCore.QRect(610, 10, 30, 30))
        self.type_chart_b1.setObjectName("type_chart_b1")
        self.type_chart_b1.setText("📊")

        Top10.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Top10)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 645, 21))
        self.menubar.setObjectName("menubar")
        Top10.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Top10)
        self.statusbar.setObjectName("statusbar")
        Top10.setStatusBar(self.statusbar)

        self.retranslateUi(Top10)
        QtCore.QMetaObject.connectSlotsByName(Top10)

    def retranslateUi(self, Top10):
        _translate = QtCore.QCoreApplication.translate
        Top10.setWindowTitle(_translate("Top10", "Top10"))
        self.type_label.setText(_translate("Top10", "Enter the type: "))
        self.type.setStatusTip(_translate("Top10", "Enter the type!"))
        self.type.setPlaceholderText(_translate("Top10", "Type"))
        self.type_header.setText(_translate("Top10", "TYPE"))
        self.type_header.setStyleSheet(
            f"background-color: {DEFAULT_TYPE_COLOR};"
            "color: white;"
            "font-weight: bold;"
            "font-size: 11pt;"
            "border-radius: 14px;"
            "padding: 2px;"
        )
        for i in range(1, 11):
            getattr(self, f"pokemon{i}").setText(_translate("Top10", f"{i}. --"))
        self.raidCounters_b1.setText(_translate("Top10", "Raid Counters"))
        self.battle_b1.setText(_translate("Top10", "Battle!"))
        self.team_b1.setText(_translate("Top10", "My Team"))
        self.lookup_b1.setText(_translate("Top10", "Look Up Pokemon"))

        set_background(self, "poke_background.jpg")

        # Signal wiring (type.returnPressed, lookup_b1.clicked) is done in
        # main.py, since it needs the shared pokedex and window-switching
        # logic that this file no longer has access to.


def scale_pixmap_cover(pixmap, target_width, target_height):
    """
    Scale a pixmap to completely fill a target_width x target_height box
    with no distortion (aspect ratio preserved) and no empty space,
    center-cropping whatever overhangs. This is what lets images of any
    aspect ratio (portrait, landscape, near-square, ...) all look
    consistent as a background.
    """
    if pixmap.isNull() or target_width <= 0 or target_height <= 0:
        return pixmap

    # Scale up so the *smaller* dimension matches the target (this is what
    # overfills the other dimension instead of leaving letterbox gaps).
    scaled = pixmap.scaled(
        target_width,
        target_height,
        QtCore.Qt.KeepAspectRatioByExpanding,
        QtCore.Qt.SmoothTransformation
    )

    # Center-crop the overhang so the result is exactly target_width x target_height.
    x = max(0, (scaled.width() - target_width) // 2)
    y = max(0, (scaled.height() - target_height) // 2)

    return scaled.copy(x, y, target_width, target_height)


def darken_color(hex_color, factor=0.6):
    """Darken a hex color by multiplying RGB values by factor (0-1)."""
    hex_color = hex_color.lstrip('#')
    r = int(hex_color[0:2], 16)
    g = int(hex_color[2:4], 16)
    b = int(hex_color[4:6], 16)

    r = max(0, int(r * factor))
    g = max(0, int(g * factor))
    b = max(0, int(b * factor))

    return f"#{r:02x}{g:02x}{b:02x}"


def set_background(ui, name_of_background, pokemon_type=None):
    print(name_of_background)

    # NOTE: this is called from retranslateUi(), which runs during
    # setupUi() -- before the window is ever shown. At that point Qt
    # hasn't laid out centralwidget against the QMainWindow yet, so
    # centralwidget.width()/height() would return Qt's default new-widget
    # size (100x30), not the real window size. Since this window is a
    # fixed-size, absolute-positioned layout (see Top10.resize(645, 595)
    # above), we use the same known design size here instead of querying
    # live (and, at this point, unreliable) widget geometry.
    widget_width = 651
    widget_height = 561

    # Make all labels black
    ui.centralwidget.setStyleSheet("""
        QLabel {
            color: black;
            font-weight: bold;

        }
    """)

    # Background
    ui.background.setGeometry(0, 0, widget_width, widget_height)

    # If type provided, use darkened type color; otherwise use background image
    if pokemon_type and pokemon_type in TYPE_COLORS:
        background_color = darken_color(TYPE_COLORS[pokemon_type], factor=0.6)
        # Clear any existing pixmap first
        ui.background.setPixmap(QtGui.QPixmap())
        ui.background.setStyleSheet(f"background-color: {background_color};")
        # Delete overlay if it exists
        if hasattr(ui, 'background_overlay') and ui.background_overlay is not None:
            try:
                ui.background_overlay.deleteLater()
            except RuntimeError:
                pass
            ui.background_overlay = None
    else:
        # Load default background image with overlay baked in
        ui.background.setStyleSheet("")  # Clear stylesheet
        pixmap = QtGui.QPixmap("img/poke_background.jpg")
        pixmap = scale_pixmap_cover(pixmap, widget_width, widget_height)

        # Create overlay painter on the pixmap
        painter = QtGui.QPainter(pixmap)
        painter.fillRect(pixmap.rect(), QtGui.QColor(255, 255, 255, 150))
        painter.end()

        ui.background.setPixmap(pixmap)

        # Delete old overlay if it exists
        if hasattr(ui, 'background_overlay') and ui.background_overlay is not None:
            try:
                ui.background_overlay.deleteLater()
            except RuntimeError:
                pass
            ui.background_overlay = None

    # Put background at the very back
    ui.background.lower()

    # Delete old overlay if it exists
    if hasattr(ui, 'background_overlay') and ui.background_overlay is not None:
        ui.background_overlay.deleteLater()

    ui.search_box.raise_()
    ui.type_label.raise_()
    ui.type.raise_()

    ui.card.raise_()
    ui.type_header.raise_()
    ui.divider.raise_()
    for i in range(1, 11):
        getattr(ui, f"pokemon{i}").raise_()
        getattr(ui, f"sprite{i}").raise_()
        getattr(ui, f"type{i}").raise_()
        getattr(ui, f"type{i}_2").raise_()
        getattr(ui, f"stats{i}").raise_()

    ui.raidCounters_b1.raise_()
    ui.battle_b1.raise_()
    ui.team_b1.raise_()
    ui.lookup_b1.raise_()
    ui.type_chart_b1.raise_()

    button_style = "QPushButton { color: black; font-size: 10pt; background-color: rgba(255, 255, 255, 220); border: 2px solid #333333; border-radius: 6px; box-shadow: 0 12px 24px rgba(0, 0, 0, 0.6); } QPushButton:hover { background-color: rgba(255, 255, 255, 240); box-shadow: 0 16px 32px rgba(0, 0, 0, 0.7); } QPushButton:pressed { background-color: rgba(230, 230, 230, 220); box-shadow: inset 0 4px 8px rgba(0, 0, 0, 0.4), 0 2px 4px rgba(0, 0, 0, 0.3); }"
    ui.raidCounters_b1.setStyleSheet(button_style)
    ui.battle_b1.setStyleSheet(button_style)
    ui.team_b1.setStyleSheet(button_style)
    ui.lookup_b1.setStyleSheet(button_style)
    ui.type_chart_b1.setStyleSheet("QPushButton { color: black; font-size: 14pt; background-color: rgba(255, 255, 255, 220); border: 2px solid #333333; border-radius: 6px; box-shadow: 0 12px 24px rgba(0, 0, 0, 0.6); } QPushButton:hover { background-color: rgba(255, 255, 255, 240); box-shadow: 0 16px 32px rgba(0, 0, 0, 0.7); } QPushButton:pressed { background-color: rgba(230, 230, 230, 220); box-shadow: inset 0 4px 8px rgba(0, 0, 0, 0.4), 0 2px 4px rgba(0, 0, 0, 0.3); }")


def handle_top(ui, pokedex, on_pokemon_click=None):

    # Get the value from the LineEdit
    type_name = ui.type.text()
    ui.type.clear()

    print("User entered: ", type_name)

    # Get Pokemon from database
    top10 = pokedex.get_top_10(type_name)

    if top10 is None:
        ui.type_header.setText("Type Not Found")
        return

    print(top10)

    name_of_background = type_name.lower() + ".jpg"
    set_background(ui, name_of_background, pokemon_type=type_name.lower())

    # Type badge + card border themed to the searched type
    color = TYPE_COLORS.get(type_name.lower(), DEFAULT_TYPE_COLOR)
    ui.type_header.setText(type_name.capitalize())
    ui.type_header.setStyleSheet(
        f"background-color: {color};"
        "color: white;"
        "font-weight: bold;"
        "font-size: 11pt;"
        "border-radius: 14px;"
        "padding: 2px;"
    )
    ui.card.setStyleSheet(
        "QFrame#card {"
        "background-color: rgba(255, 255, 255, 235);"
        f"border: 5px solid {color};"
        "border-radius: 22px;"
        "}"
    )

    # Search box matches the card border color
    ui.search_box.setStyleSheet(
        "QFrame#search_box {"
        f"background-color: {color};"
        "border-radius: 12px;"
        "}"
    )

    # Results, ranked 1-10 (previously pokemon2 accidentally showed a
    # weight value instead of the Pokemon's name -- fixed here)
    names = top10["pokemon"]
    for i in range(10):
        rank = i + 1
        pokemon_name = str(names[i]).lower()
        pokemon_display_name = str(names[i]).title()

        # Name button (clickable)
        name_btn = getattr(ui, f"pokemon{rank}")
        name_btn.setText(f"{rank}. {pokemon_display_name}")
        try:
            name_btn.clicked.disconnect()
        except TypeError:
            pass
        if on_pokemon_click:
            name_btn.clicked.connect(lambda checked, pname=pokemon_name: on_pokemon_click(pname))
        else:
            name_btn.clicked.connect(lambda checked, pname=pokemon_name, pui=ui, pdb=pokedex: _lookup_pokemon_top10(pui, pdb, pname))

        # Sprite button (clickable)
        sprite_btn = getattr(ui, f"sprite{rank}")
        try:
            sprite_btn.clicked.disconnect()
        except TypeError:
            pass
        if on_pokemon_click:
            sprite_btn.clicked.connect(lambda checked, pname=pokemon_name: on_pokemon_click(pname))
        else:
            sprite_btn.clicked.connect(lambda checked, pname=pokemon_name, pui=ui, pdb=pokedex: _lookup_pokemon_top10(pui, pdb, pname))

        # Get sprite from database
        conn = pokedex.get_connection()
        cursor = conn.cursor()
        cursor.execute("SELECT sprite, type_1, type_2 FROM pokedex WHERE LOWER(pokemon) = ?", (pokemon_name,))
        row = cursor.fetchone()
        conn.close()

        if row and row[0]:
            sprite_data = row[0]
            pixmap = QtGui.QPixmap()
            pixmap.loadFromData(sprite_data)
            if not pixmap.isNull():
                scaled = pixmap.scaled(32, 32, QtCore.Qt.KeepAspectRatio, QtCore.Qt.SmoothTransformation)
                icon = QtGui.QIcon(scaled)
                sprite_btn.setIcon(icon)
                sprite_btn.setIconSize(QtCore.QSize(32, 32))

        # Get type info
        if row:
            type_1 = row[1]
            type_2 = row[2]
            type_badge = getattr(ui, f"type{rank}")
            type_badge2 = getattr(ui, f"type{rank}_2")

            if type_1:
                type_color = TYPE_COLORS.get(str(type_1).lower(), DEFAULT_TYPE_COLOR)
                type_badge.setText(str(type_1).capitalize())
                type_badge.setStyleSheet(
                    f"font-size: 8pt; font-weight: bold; border-radius: 4px; padding: 2px; "
                    f"background-color: {type_color}; color: white;"
                )

            if type_2 and pd.notna(type_2):
                type_color2 = TYPE_COLORS.get(str(type_2).lower(), DEFAULT_TYPE_COLOR)
                type_badge2.setText(str(type_2).capitalize())
                type_badge2.setStyleSheet(
                    f"font-size: 8pt; font-weight: bold; border-radius: 4px; padding: 2px; "
                    f"background-color: {type_color2}; color: white;"
                )
                type_badge2.show()
            else:
                type_badge2.hide()

        # Get and display total stats
        total_stats = top10.iloc[i].get('total_stats', 0)
        stats_label = getattr(ui, f"stats{rank}")
        stats_label.setText(f"Total: {int(total_stats)}")


def _lookup_pokemon_top10(ui, pokedex, pokemon_name):
    """Look up a pokemon from top 10 click and display it in lookup window."""
    # Import here to avoid circular import at module load time
    import look_up

    poke_data = pokedex.get_pokemon_by_name(pokemon_name)

    if poke_data is None:
        return

    # Use the lookup function to display the pokemon
    look_up._lookup_pokemon_by_name(ui, pokedex, pokemon_name)
